# Generated by Django 3.2 on 2021-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('status', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
            ],
        ),
    ]
